import {StyleSheet} from 'react-native';

import {colorDefs, appColors} from '../../../constants/colors';

export const styles = StyleSheet.create({
  outerContainer: {
    flex: 1,
    backgroundColor: appColors.BG,
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    backgroundColor: appColors.TRANSPARENT,
  },
  flatlistWrapper: {
    flex: 1,
  },
  flatlist: {
    flex: 1,
  },
  help: {
    backgroundColor: appColors.TEXT_WHITE,
    padding: 15,
    borderRadius: 10,
    shadowOffset: {
      height: 1,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowColor: appColors.LIGHT_GREY,
    shadowRadius: 2,
    marginVertical: 6,
    marginHorizontal: 6,
    elevation: 1,
    // marginBottom: 40,
  },
  bids: {
    backgroundColor: appColors.BG,
    padding: 15,
    borderRadius: 10,
    shadowOffset: {
      height: 1,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowColor: appColors.TEXT_SEMI,
    shadowRadius: 2,
    marginVertical: 4,
    elevation: 1,
    flexDirection: 'row',
  },
  lables: {
    fontSize: 18,
    color: appColors.TEXT_DARK,
    fontWeight: 'bold',
    marginLeft: 5,
  },
  buttonWrapper: {
    marginTop: 20,
  },
  button: {
    height: 40,
    alignItems: 'center',
    borderRadius: 30,
    justifyContent: 'center',
  },
  buttonText: {
    color: appColors.TEXT_WHITE,
    fontSize: 16,
    fontWeight: 'bold',
  },
  title: {
    fontSize: 20,
    color: appColors.TEXT_DARK,
    fontWeight: 'bold',
    padding: 5,
  },
  textFields: {
    fontSize: 17,
    paddingVertical: 10,
    marginLeft: 20,
  },
  helpDetails: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignContent: 'space-between',
    marginLeft: 5,
  },
  helpDuration: {
    fontSize: 16,
    paddingVertical: 10,
    width: 250,
  },
  bidsCountWrapper: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  baseValueWrapper: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  profilePic: {
    width: 80,
    height: 80,
    resizeMode: 'contain',
    alignItems: 'flex-start',
    borderRadius: 30,
  },
  bidsWrapper: {
    flex: 1,
    paddingHorizontal: 20,
    justifyContent: 'center',
  },
  bidsTextFields: {
    fontSize: 16,
  },
  bidsDetails: {
    paddingVertical: 10,
    flex: 1,
    flexDirection: 'row',
  },
  submitButtons: {
    backgroundColor: appColors.GRADIENT_LEFT,
    padding: 10,
    width: 150,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: appColors.GRADIENT_LEFT,
    justifyContent: 'center',
    margin: 15,
    height: 40,
  },
  submitBtnText: {
    alignSelf: 'center',
    color: appColors.TEXT_WHITE,
    fontWeight: 'bold',
    fontSize: 15,
    padding: 5,
  },

  otpInput: {
    borderBottomWidth: 1,
    borderBottomColor: appColors.TEXT_SEMI,
    width: 150,
  },
  heading: {
    fontSize: 20,
    color: appColors.TEXT_DARK,
    alignSelf: 'center',
    fontWeight: 'bold',
    padding: 5,
    margin: 2,
  },
  floatingButton: {
    position: 'absolute',
    width: 70,
    height: 70,
    alignItems: 'center',
    justifyContent: 'center',
    right: 10,
    bottom: 75,
    borderRadius: 50,
    padding: 10,
  },
  lblChat: {
    padding: 10,
    color: colorDefs.WHITE,
  },
  lblDesc: {
    fontSize: 15,
    padding: 5,
  },
  rowConatiner: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  lblHelpDuration: {
    fontSize: 18,
    color: appColors.TEXT_DARK,
    fontWeight: 'bold',
  },
  lblOtp: {
    marginLeft: 20,
    fontSize: 16,
  },
  chatbtn: {
    height: 65,
    width: 65,
  },
  endHelp: {
    backgroundColor: appColors.GRADIENT_RIGHT,
    height: 40,
    justifyContent: 'center',
    borderColor: appColors.GRADIENT_LEFT,
    borderRadius: 20,
    margin: 10,
  },
  lblendHelp: {
    alignSelf: 'center',
    color: appColors.TEXT_WHITE,
  },
  centeredView: {
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: '45%',
  },
  textInput: {
    margin: 10,
    backgroundColor: appColors.TEXT_WHITE,
    borderRadius: 10,
    fontSize: 16,
    textAlignVertical: 'top',
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    width: '80%',
    marginBottom: 0,
  },
  modalSaveBtn: {
    flex: 1,
    backgroundColor: appColors.GRADIENT_LEFT,
    borderRadius: 20,
    elevation: 2,
    justifyContent: 'center',
    marginHorizontal: 5,
  },
  modalCancelBtn: {
    flex: 1,
    backgroundColor: appColors.TEXT_LIGHT,
    borderRadius: 20,
    elevation: 2,
    justifyContent: 'center',
    marginHorizontal: 5,
  },
  modalBtnsContainer: {
    flexDirection: 'row',
    width: '100%',
    height: 75,
    padding: '5%',
  },
  textStyle: {
    alignSelf: 'center',
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  getOtptext: {
    // textAlign: 'center',
    width: '75%',
    // padding: 2,
    fontSize: 12,
  },
  modalView: {
    margin: 20,
    backgroundColor: colorDefs.SMOKE_WHITE,
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    width: '90%',
  },
  modalScrollView: {
    flex: 1,
    backgroundColor: colorDefs.SEMI_TRANSPARENT,
  },
});
